/*
  This file is generated by Emacs.
*/
import "../css/index.css";
// import { Router } from "./router";
import Mustache from "mustache";

function main() {
    togglePage();
    clickHijack();
    var data = {
        playlist: [
            {
                id: 1,
                cover: "/path/to/1.png",
                name: 'Tohou',
                artist: '3L'
            },
            {
                id: 2,
                cover: "/path/to/2.png",
                name: 'Tohou',
                artist: '3L'
            }

        ]
    };
    playlistRender(data);
}

// 切换首页和歌曲播放页
var togglePage = (function() {
    let isIndex = true,
        pageIndex = document.querySelector('#index-page'),
        pagePlaying = document.querySelector('#playing-page');

    // playlist.addEventListener('scroll', function(e){
    //     console.log(e.target.scrollTop);
    //     if (e.target.scrollTop > 10) {
    //         e.target.animate([
    //             {
    //                 opacity: 0,
    //             },
    //             {
    //                 opacity: 1
    //             }
    //         ], 200);
    //         statusBar.classList.add('hidden');
    //     }
    // });

    return function(musicId=1) {
        if (isIndex) {
            // TODO: 加个切换动画
            pageIndex.classList.remove('hidden');
            pagePlaying.classList.add('hidden');
        } else {
            pageIndex.classList.add('hidden');
            pagePlaying.classList.remove('hidden');
        }
        isIndex = !isIndex;
    };
})();

// 拦截部分元素的点击事件
function clickHijack() {
    document.onclick = function(event) {
        event = event || window.event;
        var target = event.target || event.srcElement;
        if (target.tagName == 'LI' && target.className == 'btn-link') {
            target.onclick = clickBtn(target);
        }
        else if (target.tagName == 'IMG') {
            target.onclick = function(event) {
                event.cancelBubble = true;
                let id = target.attributes.getNamedItem('data-id').value;
                console.log(id);
            };
        }
        target.onclick && target.onclick(event);
    };
}

// 点击首页的三个按钮
// 歌曲列表 按钮从网络加载数据
// 我的最爱 按钮从 localstorage 加载数据
//
var clickBtn = (function() {
    let prevId = 'music', musicListData;
    return function(target){
        return function(event) {
            event.cancelBubble = true;
            let id = target.id; //target.attributes.getNamedItem('id').value;
            if (!target.classList.contains('active')) {
                target.classList.add('active');
                // 从 localstorage 加载用户的收藏曲目
                switch(id) {
                case 'music':
                    playlistRender({
                        playlist: [
                            {
                                id: 1,
                                cover: "/path/to/1.png",
                                name: 'Tohou',
                                artist: '3L'
                            },
                            {
                                id: 2,
                                cover: "/path/to/2.png",
                                name: 'Tohou',
                                artist: '3L'
                            }

                        ]
                    });
                    break;
                case 'fav':
                    playlistRender(
                        {
                            playlist: [
                                {
                                    id: 1,
                                    cover: "/path/to/1.png",
                                    name: 'Tohou',
                                    artist: '3L'
                                },
                                {
                                    id: 2,
                                    cover: "/path/to/2.png",
                                    name: 'Tohou',
                                    artist: '3L'
                                }

                            ]
                        }, false);
                    break;
                case 'result':
                    let playlist = document.querySelector('.playlist');
                    console.log("To be continuted");
                    break;
                default:
                    console.error('An error has been raised');
                }
            }
            if (prevId && prevId != id) {
                let prevBtn = document.getElementById(prevId);
                console.log(prevBtn);
                prevBtn.classList.remove('active');
            }
            prevId = target.id;
        };
    };
})();

// 列表渲染,有两种模式,第一种是 append,也就是在原有歌曲列表中插入数据,主要用于渲染 歌曲列表 按钮的结果,以及实现下拉加载功能
// 第二种模式是重新渲染列表主要用于 我的最爱 按钮的结果,目前只考虑到小量的歌曲,所以直接重新加载
var playlistRender = (function(){
    let amount = 0,
        tplSong = document.querySelector('#song-template').innerText,
        statusBar = document.querySelector('.status-bar'),
        playlist = document.querySelector('.playlist .wrapper');

    return function(data={ playlist: [] }, append=true) {
        let rendered = Mustache.render(tplSong, data);
        if (append) {
            amount += data.playlist.length;
            playlist.insertAdjacentHTML('beforeend', rendered);
            statusBar.innerHTML = "<p>当前已加载歌曲共" + amount + "首</p>";
        } else {
            playlist.innerHTML = rendered;
            statusBar.innerHTML = "<p>当前收藏歌曲共" + data.playlist.length + "首</p>";
        }
    };
})();

main();

togglePage();
// TODO: 重新编写状态栏的事件
// TODO: 收藏图标的样式以及点击事件
// TODO: 点击按钮时候的切换动画
// TODO: 播放页面的样式,以及点击歌曲时候的事件
// TODO: 搜索功能,编写后端
// TODO: 切换伪元素的 content
// TODO: 添加曲目本地文件夹做为音乐源
// TODO: 手动实现一个前端路由器
